name: docker

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set current date as env variable
        id: tagname
        run: echo "::set-output name=timestamp::$(date +'%s')"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          TAG_NAME: ${{ steps.tagname.outputs.timestamp }}
        with:
          push: true
          tags: mstruebing/blog:${{ steps.tagname.outputs.timestamp }}
